const $=id=>document.getElementById(id);
const cfg={executors:3,cores:2,partitions:24,size:1200,shuffle:12,state:200,skew:false,repartition:false,target:16};
let view='execution',technical=false,running=false,elapsed=0,last=0,model=[],total=0;
const names={execution:'Execution playground',shuffle:'Shuffles & stages',streaming:'Structured Streaming',ui:'Spark UI explorer'};
const titles={execution:['See how Spark does the work.','Turn the knobs. Run a job. Watch your data come to life.'],shuffle:['Follow the data through a shuffle.','Trace the DAG. Cross a stage boundary. See why data moves.'],streaming:['More state partitions. Same cluster.','Explore how streaming state is distributed and processed, one micro-batch at a time.'],ui:['Read the story behind the Spark UI.','Connect the running simulation to the metrics you see in a real job.']};
const specs=[['executors','Executors',1,8,1],['cores','Cores per executor',1,8,1],['partitions','Input partitions',1,96,1],['size','Data size',100,10000,100]];
function slider(key,label,min,max,step){return `<div class="control"><label for="${key}">${label}<output id="out-${key}">${key==='size'?fmt(cfg[key]):cfg[key]}</output></label><input id="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${cfg[key]}"><div class="range-ends"><span>${key==='size'?'100 MB':min}</span><span>${key==='size'?'10 GB':max}</span></div></div>`}
function fmt(n){return n>=1000?`${(n/1000).toFixed(1)} GB`:`${Math.round(n)} MB`}
function controls(){ $('sliders').innerHTML=specs.map(s=>slider(...s)).join(''); $('skew').checked=cfg.skew;$('skew').disabled=view==='streaming'; $('extra-controls').innerHTML=view==='streaming'?`<div class="state-choices"><button data-state="200" class="${cfg.state===200?'active':''}">200 state partitions</button><button data-state="800" class="${cfg.state===800?'active':''}">800 state partitions</button></div><p class="small muted">Comparison of two fresh queries with separate checkpoints.</p>`:view==='shuffle'?slider('shuffle','SQL shuffle partitions',1,96,1)+`<label class="toggle-row" style="margin-top:18px"><span><b>Add repartition()</b><small>An explicit extra shuffle before groupBy</small></span><input id="repartition" type="checkbox" ${cfg.repartition?'checked':''}></label>`+(cfg.repartition?slider('target','repartition() target',1,96,1):''):'';
$('sliders').querySelectorAll('input').forEach(bindRange);$('extra-controls').querySelectorAll('input[type=range]').forEach(bindRange);const r=$('repartition');if(r)r.onchange=()=>{cfg.repartition=r.checked;resetSimulation();controls();render()};document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{cfg.state=+b.dataset.state;resetSimulation();controls();render()})}
function bindRange(el){el.oninput=()=>{cfg[el.id]=+el.value;resetSimulation();$('out-'+el.id).textContent=el.id==='size'?fmt(cfg[el.id]):cfg[el.id];render()}}
function buildModel(){const slots=cfg.executors*cfg.cores;let stages=view==='streaming'?[{name:'Read events',n:cfg.partitions,kind:'input'},{name:'Update state + sink',n:cfg.state,kind:'state'}]:view==='shuffle'?[{name:'Read + filter',n:cfg.partitions,kind:'input'},...(cfg.repartition?[{name:'Repartition output',n:cfg.target,kind:'repartition'}]:[]),{name:'Aggregate + write',n:cfg.shuffle,kind:'aggregate'}]:[{name:'Read + transform',n:cfg.partitions,kind:'input'}];let start=0;
model=stages.map((s,si)=>{const clocks=Array(slots).fill(start);const tasks=Array.from({length:s.n},(_,id)=>{let core=clocks.indexOf(Math.min(...clocks));const hot=cfg.skew&&view!=='streaming'&&id===0&&s.n>1;const mb=cfg.size*(cfg.skew&&view!=='streaming'&&s.n>1?(hot?.45:.55/(s.n-1)):1/s.n);const duration=.22+mb/90*(s.kind==='state'?1.25:1);const task={id,core,start:clocks[core],end:clocks[core]+duration,duration,mb,hot};clocks[core]=task.end;return task});const end=Math.max(...clocks);const st={...s,id:si,start,end,tasks};start=end+.65;return st});total=model.at(-1).end}
function resetSimulation(){running=false;elapsed=0;buildModel()}
function currentStage(){return model.find(s=>elapsed<s.end)||model.at(-1)}
function taskStatus(t){return elapsed>=t.end?'done':elapsed>0&&elapsed>=t.start?'running':'pending'}
function metric(val,label){return `<div class="metric"><b>${val}</b><small>${label}</small></div>`}
function render(){const st=currentStage(),slots=cfg.executors*cfg.cores;const active=st.tasks.filter(t=>taskStatus(t)==='running'),done=st.tasks.filter(t=>taskStatus(t)==='done').length;const completed=elapsed>=total;const barrier=elapsed>0&&elapsed<st.start;
$('slots').textContent=`${cfg.executors} × ${cfg.cores} = ${slots} cores`;$('status').textContent=completed?'Job complete':barrier?'Shuffling data':elapsed===0?'Ready to run':running?'Running': 'Paused';$('run').textContent=running?'Ⅱ Pause':completed?'↺ Run again':elapsed?'▶ Resume':'▶ Run simulation';$('sim-title').textContent=view==='streaming'?'A micro-batch, many state stores':view==='shuffle'?'One DAG. Multiple stages.':view==='ui'?'Spark UI · teaching edition':'From partitions to parallel work';$('sim-note').textContent=technical?'Fixed cluster · spark.task.cpus = 1 · AQE disabled · no retries':'A partition becomes one task in each stage that processes it.';
$('metrics').innerHTML=metric(st.n,view==='streaming'&&st.kind==='state'?'STATE TASKS':'TASKS IN STAGE')+metric(slots,'TOTAL CORE SLOTS')+metric(Math.ceil(st.n/slots),'MIN. TASK WAVES')+metric(`${done}/${st.n}`,'TASKS COMPLETE');
let html='';if(view==='shuffle'||view==='streaming')html+=dag(st);
if(view==='streaming'){html+=`${stateComparison()}<div class="stream-banner"><b>${cfg.state} state partitions ≠ ${cfg.state} cores</b><p>${cfg.executors} executors × ${cfg.cores} cores = ${slots} simultaneous tasks. The stateful stage needs at least ${Math.ceil(cfg.state/slots)} waves on this cluster.</p></div><div class="visual-label">PARTITIONED STATE STORES <span>one store per partition for this operator</span></div><div class="state-grid">${Array.from({length:cfg.state},(_,i)=>`<div class="state-cell ${st.kind==='state'?taskStatus(st.tasks[i]):''}" title="State partition ${i} · key hash mod ${cfg.state}"></div>`).join('')}</div><p class="state-label">Each square represents one logical state partition. Tasks update assigned stores and commit a checkpoint version. Stores are logical units, not dedicated machines.</p>`}
if(view==='ui'){html+=ui(st)}else{html+=`<div class="visual-label">${st.kind==='state'?'STATE UPDATE TASK QUEUE':'DATA PARTITIONS → TASK QUEUE'}<span>${fmt(cfg.size)} total · ${st.n} partitions</span></div><div class="partition-grid">${st.tasks.slice(0,96).map(t=>`<div class="partition ${taskStatus(t)} ${t.hot?'hot':''}" title="Partition ${t.id}: ${fmt(t.mb)} · ${taskStatus(t)}">${st.kind==='state'?'S':'P'}${t.id}${t.hot?' ▴':''}</div>`).join('')}</div>${st.n>96?`<p class="state-label">First 96 task cards shown. All ${st.n} tasks are scheduled; the store grid above shows every state partition.</p>`:''}<div class="flow">↓ <small>${barrier?'SHUFFLE EXCHANGE':elapsed===0?'DRIVER SCHEDULES TASKS':`${active.length} RUNNING · ${st.n-done-active.length} QUEUED`}</small> ↓</div>`+executorView(st)}
html+=`<div class="legend"><span><i></i>Idle / queued</span><span><i class="r"></i>Running</span><span><i class="d"></i>Completed</span><span><i class="h"></i>Skewed</span></div>`;$('visual').innerHTML=html;document.body.classList.toggle('is-running',running);$('scrub').value=Math.round(elapsed/total*1000);$('clock').textContent=elapsed.toFixed(1)+'s / '+total.toFixed(1)+'s';$('engine-util').textContent=Math.round(active.length/slots*100)+'% core utilization';$('engine-state').textContent=barrier?'SHUFFLE BOUNDARY · EXCHANGING DATA':completed?'ALL TASKS COMPLETE':elapsed===0?'PARTITIONS → TASKS → CORES':`${active.length} ACTIVE · ${st.n-done-active.length} WAITING`;drawScene();
const waves=Math.ceil(st.n/slots);$('insight').textContent=barrier?'Shuffle boundary: the upstream stage has finished. Data is exchanged before downstream tasks begin.':completed?'All tasks finished. Notice that the cluster size stayed constant throughout the job.':cfg.skew&&view!=='streaming'?'Watch the amber task: its larger partition keeps a core busy after other cores finish. The next stage waits for every upstream task.':st.n<slots?`${st.n} tasks can use only ${st.n} of ${slots} cores. ${slots-st.n} cores have no work in this stage.`:`${st.n} tasks share ${slots} cores. At least ${waves} waves are needed; a free core picks up the next queued task.`;
updateCode();$('take-title').textContent=view==='streaming'?'State is data, not hardware.':view==='shuffle'?'A shuffle changes the plan.':cfg.skew?'The slowest task sets the pace.':'More partitions. Same cluster.';$('take-text').textContent=view==='streaming'?`At 800 partitions, keys are split into more state stores than at 200. With ${slots} cores, only ${slots} tasks can run at once. More partitions reduce average state per task but add scheduling, store and checkpoint overhead.`:view==='shuffle'?'Narrow operations like filter can be pipelined within a stage. groupBy gathers matching keys through a shuffle. Explicit repartition(n) adds an exchange and chooses its output partition count; the SQL setting controls the aggregation shuffle here.':cfg.skew?'A hot key or uneven data can make a single partition much larger. Other cores become idle while its task continues. Increasing the partition count alone cannot split one hot grouping key.':'A partition is a slice of data. A task processes that slice for a stage. Executors host cores, and cores provide task slots. Extra partitions wait their turn; extra cores help only when enough tasks are available.';
$('technical-note').innerHTML=technical?`<div class="tech-note">${view==='streaming'?'Spark 3.5 checkpoint rule: do not change spark.sql.shuffle.partitions when restarting the same stateful query. This comparison uses fresh checkpoints and does not migrate existing state. Input replay and sink semantics must be planned separately.':'Assumptions: fixed executors, one CPU per task, no failures, no speculative copies, no AQE coalescing. “Waves” is a lower bound, not a Spark scheduler barrier. Real duration depends on I/O, locality, spill and contention.'}</div>`:view==='streaming'?'<div class="tech-note">Changing 200 → 800 compares new queries. In Spark 3.5, changing this setting on an existing stateful checkpoint is not a supported restart.</div>':'';$('docs').href=view==='streaming'?'https://spark.apache.org/docs/3.5.7/structured-streaming-programming-guide.html':'https://spark.apache.org/docs/3.5.7/rdd-programming-guide.html'}
function executorView(st){return `<div class="visual-label">EXECUTOR CLUSTER <span>${cfg.executors} executors · ${cfg.cores} cores each</span></div><div class="executors" style="grid-template-columns:repeat(${Math.min(cfg.executors,4)},1fr)">${Array.from({length:cfg.executors},(_,e)=>`<div class="executor"><div class="executor-head"><b>Executor ${e+1}</b><span>● online</span></div><div class="core-grid" style="grid-template-columns:repeat(${Math.min(cfg.cores,4)},1fr)">${Array.from({length:cfg.cores},(_,c)=>{const task=st.tasks.find(t=>t.core===e*cfg.cores+c&&taskStatus(t)==='running');return `<div class="core ${task?'running':''} ${task?.hot?'hot':''}"><b>${task?'Task '+task.id:'Idle'}</b><small>Core ${c+1}${task?' · '+Math.min(100,Math.round((elapsed-task.start)/task.duration*100))+'%':''}</small>${task?`<span class="progress" style="width:${(elapsed-task.start)/task.duration*100}%"></span>`:''}</div>`}).join('')}</div></div>`).join('')}</div>`}
function dag(st){return `<div class="dag">${model.map((s,i)=>`${i?'<span>→</span><div class="dag-node boundary">Shuffle<small>wide dependency</small></div><span>→</span>':''}<div class="dag-node ${st.id===i?'current':''}">${s.name}<small>Stage ${i} · ${s.n} tasks</small></div>`).join('')}</div><div class="stage-strip">${model.map(s=>`<div class="stage-pill ${s.id===st.id?'current':''}">Stage ${s.id}: ${s.name}<small>${elapsed>=s.end?'Complete':elapsed<s.start?'Waiting':'Active'} · ${s.tasks.filter(t=>taskStatus(t)==='done').length}/${s.n} tasks</small></div>`).join('')}</div>`}
function ui(st){return `<div class="ui-tabs">Jobs Stages Executors <span style="color:#95a28d">Simulated</span></div><table class="ui-table"><thead><tr><th>Stage</th><th>Status</th><th>Tasks</th><th>Progress</th></tr></thead><tbody>${model.map(s=>{const d=s.tasks.filter(t=>taskStatus(t)==='done').length;return `<tr><td>${s.id} · ${s.name}</td><td>${elapsed>=s.end?'Complete':elapsed<s.start?'Pending':elapsed===0?'Ready':'Active'}</td><td>${d}/${s.n}</td><td><div class="table-progress"><i style="width:${d/s.n*100}%"></i></div></td></tr>`}).join('')}</tbody></table><div class="visual-label">TASK TIMELINE <span>${elapsed.toFixed(1)} / ${total.toFixed(1)} simulated seconds</span></div><div class="timeline">${Array.from({length:cfg.executors*cfg.cores},(_,c)=>`<div class="timeline-row"><span>E${Math.floor(c/cfg.cores)+1} C${c%cfg.cores+1}</span><div>${st.tasks.filter(t=>t.core===c&&elapsed>=t.start).map(t=>`<i title="Task ${t.id}" style="left:${t.start/total*100}%;width:${(Math.min(elapsed,t.end)-t.start)/total*100}%;background:${t.hot?'#e6b25d':'#a7d5b5'}"></i>`).join('')}</div></div>`).join('')}</div>`+executorView(st)}
function updateCode(){const slots=cfg.executors*cfg.cores;let code=`# Fixed cluster: ${cfg.executors} executors × ${cfg.cores} cores\n# Submit with --num-executors ${cfg.executors} --executor-cores ${cfg.cores}\n# Synthetic data: displayed size is a teaching parameter\nrdd = sc.parallelize(range(10000), ${cfg.partitions})\ndf = spark.createDataFrame(rdd.map(lambda x: (x, x % 20)),\n                           ["value", "key"])\n`;if(view==='streaming'){code=`# Same cluster: ${cfg.executors} executors, ${slots} cores\nfrom pyspark.sql import functions as F\nspark.conf.set("spark.sql.shuffle.partitions", "${cfg.state}")\nevents = spark.readStream.format("rate").load()\ncounts = events.groupBy((F.col("value") % 1000).alias("key")).count()\nquery = (counts.writeStream.format("console")\n    .outputMode("update")\n    .option("checkpointLocation", "/tmp/fresh-state-${cfg.state}")\n    .start())\n# Use a new checkpoint for this comparison (Spark 3.5).`;}else if(view==='shuffle'){code+=`spark.conf.set("spark.sql.adaptive.enabled", "false")\nspark.conf.set("spark.sql.shuffle.partitions", "${cfg.shuffle}")\n${cfg.repartition?`df = df.repartition(${cfg.target})  # explicit shuffle\n`:''}result = df.filter("value >= 0").groupBy("key").count()\nresult.write.mode("overwrite").parquet("/tmp/key-counts")`; }else{code+=`result = df.selectExpr("value * 2 AS doubled")\nresult.write.mode("overwrite").parquet("/tmp/doubled")`;}if(technical&&view!=='streaming')code+='\n# inspect the physical plan before triggering the write:\nresult.explain("formatted")';$('code').textContent=code;$('code-title').textContent=view==='streaming'?'PySpark · stateful micro-batch':'PySpark · batch job';$('code-note').textContent=view==='streaming'?'The stateful operator has its own partitioning. Input partition and size controls model an illustrative source, independent of the rate example.':'Illustrative code uses synthetic records. Data size and skew affect simulation timing, not the generated sample. Core counts are deployment settings.'}
function switchView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===v));$('crumb').textContent=names[v];$('title').textContent=titles[v][0];$('subtitle').textContent=titles[v][1];resetSimulation();controls();render()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('skew').onchange=()=>{cfg.skew=$('skew').checked;resetSimulation();render()};$('run').onclick=()=>{if(elapsed>=total)elapsed=0;running=!running;last=performance.now();render()};$('step').onclick=()=>{running=false;const next=model.flatMap(s=>s.tasks.flatMap(t=>[t.start,t.end])).filter(t=>t>elapsed+.001);elapsed=elapsed===0?.002:Math.min(total,next.length?Math.min(...next)+.002:total);render()};$('restart').onclick=()=>{resetSimulation();render()};$('reset').onclick=()=>{Object.assign(cfg,{executors:3,cores:2,partitions:24,size:1200,shuffle:12,state:200,skew:false,repartition:false,target:16});resetSimulation();controls();render()};$('beginner').onclick=()=>mode(false);$('technical').onclick=()=>mode(true);function mode(t){technical=t;document.body.classList.toggle('technical-mode',t);$('beginner').classList.toggle('active',!t);$('technical').classList.toggle('active',t);render()};$('present').onclick=()=>document.body.classList.toggle('presentation');$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('code').textContent);$('copy').textContent='Copied ✓';setTimeout(()=>$('copy').textContent='Copy code ⧉',1500)}catch{$('copy').textContent='Select code to copy'}};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{Object.assign(cfg,{executors:3,cores:2,partitions:b.dataset.preset==='idle'?3:24,skew:b.dataset.preset==='skew'});resetSimulation();controls();render()});
let rendered=0;function tick(now){if(running){elapsed=Math.min(total,elapsed+(now-last)/1000*+$('speed').value);if(elapsed>=total)running=false;if(now-rendered>100||!running){render();rendered=now}}last=now;if(running)drawScene();requestAnimationFrame(tick)}switchView('execution');requestAnimationFrame(tick);
$('scrub').oninput=()=>{running=false;elapsed=total*+$('scrub').value/1000;render()};
$('download').onclick=async()=>{try{const clone=document.documentElement.cloneNode(true);for(const link of clone.querySelectorAll('link[rel=stylesheet]')){const style=document.createElement('style');style.textContent=await (await fetch(link.href)).text();link.replaceWith(style)}for(const script of clone.querySelectorAll('script[src]')){script.textContent=await (await fetch(script.src)).text();script.removeAttribute('src')}const html='<!doctype html>\n'+clone.outerHTML;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html'}));a.download='PySpark Under the Hood.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch{$('download').textContent='Use the portable HTML copy'}};
window.addEventListener('resize',drawScene);

function stateComparison(){const slots=cfg.executors*cfg.cores;return `<div class="state-comparison">${[200,800].map(n=>`<div class="compare-card ${cfg.state===n?'chosen':''}"><span>STATE PARTITIONS</span><b>${n}</b><div class="compare-bars">${Array.from({length:n===200?12:48},()=>'<i></i>').join('')}</div><small>${Math.ceil(n/slots)} minimum waves · same ${slots} cores</small></div>`).join('')}<div class="compare-equals"><b>=</b><span>same<br>hardware</span></div></div>`}
function drawScene(){const canvas=$('engine');if(!canvas||!canvas.getContext)return;const ctx=canvas.getContext('2d');if(!ctx)return;const w=canvas.clientWidth||700,h=250,dpr=window.devicePixelRatio||1;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const st=currentStage(),slots=cfg.executors*cfg.cores;const left=54,mid=w*.43,right=w-85;const top=50,space=150/cfg.executors;
ctx.font='10px system-ui';ctx.textBaseline='middle';
for(let x=15;x<w;x+=20)for(let y=15;y<h;y+=20){ctx.fillStyle='#ffffff0b';ctx.beginPath();ctx.arc(x,y,1,0,Math.PI*2);ctx.fill()}
const grad=ctx.createRadialGradient(mid,125,5,mid,125,140);grad.addColorStop(0,'#38bda51c');grad.addColorStop(1,'#38bda500');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
function round(x,y,ww,hh,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,ww,hh,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
function path(y,color){ctx.beginPath();ctx.moveTo(mid+27,125);ctx.bezierCurveTo(mid+80,125,right-75,y,right-38,y);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.stroke()}
ctx.strokeStyle='#466b74';ctx.setLineDash([3,6]);ctx.beginPath();ctx.moveTo(left+25,125);ctx.lineTo(mid-30,125);ctx.stroke();ctx.setLineDash([]);
for(let e=0;e<cfg.executors;e++){const y=top+space*(e+.5);path(y,'#41606b');const active=st.tasks.filter(t=>Math.floor(t.core/cfg.cores)===e&&taskStatus(t)==='running');round(right-37,y-14,91,28,6,active.length?'#154b45':'#243a44',active.length?'#46bca0':'#45616c');ctx.fillStyle='#cadce1';ctx.font='9px system-ui';ctx.fillText('EXEC '+(e+1),right-28,y-3);for(let c=0;c<cfg.cores;c++){const task=active.find(t=>t.core%cfg.cores===c);ctx.fillStyle=task?.hot?'#ffc46b':task?'#58e4b8':'#57707a';ctx.beginPath();ctx.arc(right-27+c*72/Math.max(cfg.cores,1),y+7,2.1,0,Math.PI*2);ctx.fill()}}
for(let i=0;i<6;i++){const x=left-20+(i%2)*21,y=92+Math.floor(i/2)*24;round(x,y,15,17,3,'#264957','#517887');ctx.fillStyle='#8ebec6';ctx.fillRect(x+4,y+5,7,2);ctx.fillRect(x+4,y+10,5,2)}
round(mid-30,98,60,54,12,'#214d50','#5ebda4');ctx.fillStyle='#86f0cb';ctx.font='22px system-ui';ctx.textAlign='center';ctx.fillText('✳',mid,118);ctx.fillStyle='#c6e7dd';ctx.font='8px system-ui';ctx.fillText('DRIVER',mid,141);ctx.textAlign='left';ctx.fillStyle='#8ba8b1';ctx.font='9px system-ui';ctx.fillText('PARTITIONS',left-26,65);ctx.fillText('EXECUTOR CORES',right-44,28);ctx.textAlign='center';ctx.fillText(st.name.toUpperCase()+' · STAGE '+st.id,mid,221);ctx.textAlign='left';
const shuffle=elapsed>0&&elapsed<st.start;
if(shuffle){ctx.strokeStyle='#f2b969';ctx.lineWidth=1.3;for(let e=0;e<cfg.executors;e++){const y=top+space*(e+.5);ctx.beginPath();ctx.moveTo(right-38,y);ctx.bezierCurveTo(mid,y,mid,200,Math.max(left,mid-60),165);ctx.stroke()}const q=Math.min(1,Math.max(0,(elapsed-(st.start-.65))/.65));for(let e=0;e<cfg.executors;e++){const sy=top+space*(e+.5),x0=right-38,x1=mid,x2=mid,x3=Math.max(left,mid-60);const x=(1-q)**3*x0+3*(1-q)**2*q*x1+3*(1-q)*q*q*x2+q**3*x3;const y=(1-q)**3*sy+3*(1-q)**2*q*sy+3*(1-q)*q*q*200+q**3*165;ctx.shadowBlur=9;ctx.shadowColor='#ffce89';round(x-4,y-4,8,8,2,'#ffce89');ctx.shadowBlur=0}ctx.fillStyle='#ffce89';ctx.textAlign='center';ctx.fillText('EXCHANGE · STAGE BARRIER',mid,185);ctx.textAlign='left'}
if(elapsed>0&&elapsed<total){const flight=.45;const recent=st.tasks.filter(t=>elapsed>=t.start&&elapsed-t.start<Math.min(flight,t.duration*.35)).slice(-32);for(const t of recent){const p=Math.min(1,(elapsed-t.start)/Math.min(flight,t.duration*.35)),y=top+space*(Math.floor(t.core/cfg.cores)+.5);let x,yy;if(p<.35){x=left+25+(mid-left-55)*p/.35;yy=125}else{const q=(p-.35)/.65;const x0=mid+27,x1=mid+80,x2=right-75,x3=right-38;x=(1-q)**3*x0+3*(1-q)**2*q*x1+3*(1-q)*q*q*x2+q**3*x3;yy=(1-q)**3*125+3*(1-q)**2*q*125+3*(1-q)*q*q*y+q**3*y}ctx.shadowBlur=12;ctx.shadowColor=t.hot?'#eaba63':'#54ddb6';round(x-5,yy-5,10,10,3,t.hot?'#ffc46b':'#6af0c3');ctx.shadowBlur=0}
for(const t of st.tasks.filter(t=>taskStatus(t)==='running').slice(0,64)){const y=top+space*(Math.floor(t.core/cfg.cores)+.5);const p=(elapsed-t.start)/t.duration;ctx.strokeStyle=t.hot?'#ffc46b':'#58dfb5';ctx.lineWidth=2;ctx.beginPath();ctx.arc(right+43,y-3,6,-Math.PI/2,-Math.PI/2+p*Math.PI*2);ctx.stroke()}}
}
